// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIqt9uSe5Rq9u7oP5gm1kLEI-B7rtNO6o',
    appId: '1:602799286788:web:2d2acd6733028988316351',
    messagingSenderId: '602799286788',
    projectId: 'portfolio-7ca20',
    authDomain: 'portfolio-7ca20.firebaseapp.com',
    storageBucket: 'portfolio-7ca20.firebasestorage.app',
    measurementId: 'G-WHG830330X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkmq_Bf8CjiTjqK2Y4mLviojz00S2BGLM',
    appId: '1:602799286788:android:115c3c0d5b01fedf316351',
    messagingSenderId: '602799286788',
    projectId: 'portfolio-7ca20',
    storageBucket: 'portfolio-7ca20.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4dcYQ9AqaL7oP1HUJGs-mDu4hlnuEjYI',
    appId: '1:602799286788:ios:0d2bdc2c845969f2316351',
    messagingSenderId: '602799286788',
    projectId: 'portfolio-7ca20',
    storageBucket: 'portfolio-7ca20.firebasestorage.app',
    iosBundleId: 'com.example.portfolioAdmin',
  );
}
